import type { AgreementsContentMap } from "@/types";

export const agreementsContent = {
  agreementsPage: {
    title: "الاتفاقات",
    subtitle: "تابع كل اتفاقات الدفع، حالات المراحل، والدفعات المرتبطة بها من مكان واحد.",
    createLabel: "إنشاء اتفاق جديد",
    exportLabel: "تصدير",
    filterLabel: "تصفية",
    searchPlaceholder: "ابحث باسم المشروع أو العميل...",
    filterChips: ["الكل", "نشطة", "بانتظار الموافقة", "مراجعة AI", "جاهزة للصرف", "مغلقة"],
    metrics: [
      { key: "all", label: "كل الاتفاقات", value: "24", helper: "8 اتفاقات نشطة", tone: "purple", icon: "file" },
      { key: "pending", label: "بانتظار موافقة العميل", value: "5", helper: "دعوات مرسلة", tone: "amber", icon: "clock" },
      { key: "review", label: "تحت المراجعة", value: "3", helper: "مراجعات عميل أو AI", tone: "violet", icon: "sparkles" },
      { key: "ready", label: "جاهزة للصرف", value: "$3,090", helper: "6 دفعات جاهزة", tone: "emerald", icon: "dollar" },
    ],
    tableTitle: "قائمة الاتفاقات",
    tableBadge: "24 اتفاق",
    tableHeaders: ["المشروع", "العميل", "المبلغ الإجمالي", "المرحلة الحالية", "الحالة", "آخر تحديث", "الإجراءات"],
    agreements: [
      {
        id: "agr-078",
        project: "تصميم صفحة هبوط - Dhaman",
        code: "AGR-00078",
        client: "فهد العتيبي",
        clientInitial: "ف",
        clientTone: "violet",
        amount: "$450.00",
        stage: "المرحلة 2/3",
        status: "نشط",
        statusTone: "active",
        lastUpdate: "منذ ساعتين",
      },
      {
        id: "agr-077",
        project: "تطوير لوحة تحكم ذكية",
        code: "AGR-00077",
        client: "سارة خالد",
        clientInitial: "س",
        clientTone: "blue",
        amount: "$1,800.00",
        stage: "انتظار التسليم",
        status: "مراجعة AI",
        statusTone: "review",
        lastUpdate: "منذ 5 ساعات",
      },
      {
        id: "agr-076",
        project: "هوية بصرية شاملة",
        code: "AGR-00076",
        client: "مؤسسة الحلول المبتكرة",
        clientInitial: "م",
        clientTone: "emerald",
        amount: "$620.00",
        stage: "المرحلة 1/4",
        status: "بانتظار الموافقة",
        statusTone: "pending",
        lastUpdate: "منذ يوم",
      },
      {
        id: "agr-075",
        project: "تطبيق موبايل - متجر إلكتروني",
        code: "AGR-00075",
        client: "أحمد سالم",
        clientInitial: "أ",
        clientTone: "amber",
        amount: "$3,200.00",
        stage: "تم الإنجاز",
        status: "جاهز للصرف",
        statusTone: "ready",
        lastUpdate: "منذ يومين",
      },
      {
        id: "agr-074",
        project: "تطوير متجر متعدد اللغات",
        code: "AGR-00074",
        client: "نورة منصور",
        clientInitial: "ن",
        clientTone: "violet",
        amount: "$2,150.00",
        stage: "المرحلة 3/5",
        status: "نشط",
        statusTone: "active",
        lastUpdate: "منذ 3 أيام",
      },
    ],
    aiTitle: "توصيات AI",
    aiTips: [
      { label: "لديك 3 اتفاقات بانتظار مراجعة العميل منذ أكثر من 48 ساعة. ننصح بإرسال تذكير.", tone: "amber" },
      { label: "تم الانتهاء من مراجعة بنود مشروع Dhaman. الاتفاق جاهز للإرسال الآن.", tone: "emerald" },
    ],
    goalsTitle: "أهداف الشهر",
    monthlyGoals: [
      { label: "توقيع اتفاقات", value: "80%", progress: 80, tone: "violet" },
      { label: "تحصيل دفعات", value: "62%", progress: 62, tone: "emerald" },
    ],
    activityTitle: "نشاط المنصة",
    activityValue: "142",
    activityDescription: "اتفاق تم حمايته هذا الأسبوع",
  },
  createAgreementPage: {
    backLabel: "العودة للاتفاقات",
    eyebrow: "إنشاء اتفاق جديد",
    title: "إنشاء اتفاق جديد",
    subtitle: "أدخل تفاصيل المشروع والعميل، ثم دع ضمان ينشئ خطة دفع واضحة على مراحل.",
    progressTitle: "مساعدة إنشاء الاتفاق",
    progressValue: "50%",
    steps: [
      { label: "بيانات المشروع", status: "active" },
      { label: "بيانات العميل", status: "upcoming" },
      { label: "تفاصيل الدفع", status: "done" },
      { label: "سياسات الاتفاق", status: "done" },
    ],
    helpTitle: "ماذا سيقوم ضمان؟",
    helpItems: [
      { label: "تحليل المشروع" },
      { label: "اقتراح مراحل ذكية" },
      { label: "تقدير الجدول" },
      { label: "سياسات اتفاق" },
      { label: "تنبيهات للعميل" },
    ],
    summaryTitle: "ملخص الاتفاق",
    summaryItems: [
      { label: "قيمة الاتفاق", value: "$450" },
      { label: "العملة", value: "USD" },
      { label: "طريقة التقسيم", value: "ذكي AI" },
    ],
    aiButtonLabel: "توليد خطة الدفع",
    sections: {
      project: {
        title: "بيانات المشروع",
        description: "معلومات المشروع الأساسية لإنشاء خطة دفع مناسبة للمشروع.",
        nameLabel: "اسم المشروع",
        namePlaceholder: "مثال: تصميم صفحة هبوط لشركة ناشئة",
        descriptionLabel: "وصف المشروع",
        descriptionPlaceholder: "اكتب وصفاً مختصراً لما سيتم تقديمه، النطاق المتوقع، وأهم المخرجات.",
        durationLabel: "مدة التنفيذ المتوقعة",
        durationPlaceholder: "مثال: 14 يوم",
        serviceLabel: "نوع الخدمة",
        servicePlaceholder: "اختياري",
        deliveryLabel: "تاريخ التسليم المتوقع",
      },
      client: {
        title: "بيانات العميل",
        description: "معلومات التواصل مع العميل لإرسال الاتفاق.",
        nameLabel: "اسم العميل",
        namePlaceholder: "مثال: شركة المدار",
        emailLabel: "البريد الإلكتروني للعميل",
        emailPlaceholder: "client@email.com",
        phoneLabel: "رقم الهاتف",
        phonePlaceholder: "اختياري",
      },
      payment: {
        title: "تفاصيل الدفع",
        description: "قيمة الاتفاق وطريقة تقسيم الدفعات.",
        amountLabel: "قيمة الاتفاق",
        amountPlaceholder: "450",
        currencyLabel: "العملة",
        methodsLabel: "طريقة تقسيم الدفعات",
        methods: [{ label: "ذكي AI", active: true }, { label: "بناءً على المراحل" }, { label: "تقسيم يدوي" }],
        milestonesLabel: "عدد المراحل المقترح",
        milestones: ["تلقائي", "2", "3", "4", "5"],
      },
      policies: {
        title: "سياسات الاتفاق",
        description: "اختر السياسات التي تريد تضمينها في الاتفاق.",
        options: [{ label: "سياسة التأخير", active: true }, { label: "سرية البيانات" }, { label: "الملكية الفكرية" }, { label: "المراجعة والاعتراض" }],
        note: "سيقوم ضمان بإضافة بنود مناسبة لكل نوع خدمة لضمان حقوق العميل والمستقل.",
      },
    },
    saveDraftLabel: "حفظ كمسودة",
    generateLabel: "توليد اتفاق ذكي باستخدام AI",
    footerNote: "يمكنك مراجعة وتعديل كل المراحل والسياسات قبل إرسال الاتفاق للعميل.",
  },
  reviewAgreementPage: {
    backLabel: "العودة لتعديل بيانات المشروع",
    sendLabel: "إرسال الاتفاق للعميل",
    draftLabel: "حفظ كمسودة",
    warningLabel: "تحتاج مراجعة قبل الإرسال",
    checklistTitle: "جاهزية الاتفاق",
    checklistItems: [
      { label: "بيانات المشروع مكتملة", done: true },
      { label: "بيانات العميل مكتملة", done: true },
      { label: "المراحل موزعة بوضوح", done: true },
      { label: "سياسات الاتفاق مفعلة", done: true },
      { label: "تحذير مصطلحات التسليم" },
    ],
    financialTitle: "التقسيم المالي",
    financialMetrics: [
      { label: "إجمالي الاتفاق", value: "$450", tone: "emerald" },
      { label: "عدد المراحل", value: "3" },
      { label: "أول دفعة", value: "$150" },
      { label: "آخر دفعة", value: "$100" },
    ],
    chartValues: [34, 34, 22],
    reviewTitle: "مراجعة جودة العقد",
    reviewAction: "Review Agreement",
    reviewProgress: "AI reviewed: 6/29",
    aiSummary: "تمت مراجعة الخطة وإضافة ملاحظات لتحسين وضوح التسليمات قبل الإرسال.",
    inviteTitle: "معاينة دعوة العميل",
    inviteDescription: "سيستلم العميل رابطاً لمراجعة الاتفاق والموافقة عليه.",
    inviteLink: "/invite/dhmn-8K29",
    deliveryWarning: "الاتفاق واضح، لكن يحتاج احتمالية الخلاف عند التسليم.",
    heroTitle: "مراجعة الاتفاق قبل الإرسال",
    heroDescription: "راجع المراحل، السياسات، وملاحظات الذكاء الاصطناعي قبل إرسال الاتفاق للعميل.",
    projectTitle: "تصميم صفحة هبوط - Dhaman",
    projectDescription: "تصميم Landing Page احترافية لشركة ناشئة مع تجربة استخدام متجاوبة ونسخة Desktop واضحة.",
    projectMetrics: [
      { label: "إجمالي الاتفاق", value: "$450" },
      { label: "مدة التنفيذ", value: "14 يوم" },
      { label: "العملة", value: "USD" },
      { label: "الحالة", value: "مسودة", tone: "violet" },
    ],
    milestonesTitle: "مراحل الدفع المقترحة",
    milestonesDescription: "يمكنك تعديل اسم المرحلة، القيمة، والمدة قبل إرسال الاتفاق.",
    milestones: [
      {
        number: "1",
        title: "المرحلة الأولى: التخطيط والوايرفريم الأولي",
        amount: "$150",
        duration: "5 أيام",
        badge: "محسوبة عبر AI",
        badgeTone: "emerald",
        tasks: ["تحليل brief العميل", "رسم Wireframe للشاشة الرئيسية", "تحديد User journey", "اعتماد الاتجاه البصري الأول"],
      },
      {
        number: "2",
        title: "المرحلة الثانية: تصميم الواجهة النهائية",
        amount: "$200",
        duration: "6 أيام",
        badge: "تحتاج ضبط المراجعة النهائية",
        badgeTone: "amber",
        tasks: ["تصميم واجهة Landing Page كاملة", "تصميم الأقسام والمحتوى النهائي", "إعداد نسخة Desktop واضحة", "تسليم نسخة قابلة للمراجعة"],
      },
      {
        number: "3",
        title: "المرحلة الثالثة: التسليم النهائي",
        amount: "$100",
        duration: "3 أيام",
        badge: "تحتاج ضبط المراجعة النهائية",
        badgeTone: "amber",
        tasks: ["تسليم الملفات النهائية", "تسليم الملفات والمصادر", "تهيئة المخرجات للعميل", "تنفيذ تعديلات نهائية خفيفة"],
      },
    ],
    addMilestoneLabel: "إضافة مرحلة جديدة",
    policiesTitle: "سياسات الاتفاق",
    policiesDescription: "هذه السياسات ستظهر للعميل عند الموافقة على الاتفاق.",
    policies: [
      { title: "سياسة التأخير", description: "يحق للعميل طلب مراجعة التسليم عند تأخر تنفيذ أي مرحلة عن موعدها المحدد.", tone: "amber" },
      { title: "سياسة الإلغاء", description: "يمكن للعميل إلغاء الاتفاق قبل اعتماد المرحلة الأولى، وتطبق رسوم العمل المنجز فقط.", tone: "red" },
      { title: "سرية البيانات والاعتراض", description: "يجب على الطرفين الحفاظ على سرية المعلومات وعدم مشاركة أي مواد خارج الاتفاق.", tone: "violet" },
      { title: "سياسة الطلبات الإضافية", description: "أي طلب خارج نطاق المشروع يحتاج موافقة الطرفين وقد يضيف مدة أو تكلفة جديدة.", tone: "blue" },
    ],
    aiNotesTitle: "ملاحظات AI على وضوح الاتفاق",
    aiNotesAction: "تحسين البند تلقائياً",
    aiNotes: [
      { label: "وصف تسليم المرحلة الثانية قد يحتاج إلى تفصيل أكثر لتجنب خلافات المراجعة." },
      { label: "ينصح بتحديد عدد التصاميم النهائية، مثل Desktop و Mobile، بشكل واضح." },
    ],
    footerBackLabel: "الرجوع وتعديل بيانات المشروع",
    footerNote: "بعد الإرسال، سيتمكن العميل من مراجعة الاتفاق والموافقة عليه أو طلب تعديلات.",
  },
  agreementWorkspacePage: {
    backLabel: "الاتفاقات",
    title: "مساحة عمل الاتفاق",
    subtitle: "تابع حالة الاتفاق، المراحل، الدفعات، والتحديثات التشغيلية من مكان واحد.",
    submitLabel: "تقديم تسليم",
    portalLabel: "عرض بوابة العميل",
    copyInviteLabel: "نسخ رابط الدعوة",
    projectTitle: "تصميم صفحة هبوط لشركة ناشئة",
    projectDescription: "تمت موافقة العميل على الاتفاق وبدأ التنفيذ.",
    statusLabel: "نشط",
    progressLabel: "تقدم الاتفاق",
    progressValue: "33%",
    summaryMetrics: [
      { label: "العميل", value: "شركة المدار", tone: "blue" },
      { label: "إجمالي الاتفاق", value: "$450 USD", tone: "emerald" },
      { label: "التقدم", value: "مرحلة 1 من 3", tone: "violet" },
      { label: "تاريخ الإنشاء", value: "منذ 3 أيام", tone: "amber" },
      { label: "آخر تحديث", value: "منذ ساعتين", tone: "violet" },
    ],
    milestonesTitle: "مراحل الاتفاق",
    milestonesDescription: "تابع كل مرحلة، حالة الدفعة المرتبطة بها، وما إذا كانت بانتظار التسليم أو المراجعة.",
    milestones: [
      {
        number: "1",
        title: "المرحلة الأولى: الهيكل والتصميم الأولي",
        amount: "$150",
        due: "بعد يومين",
        status: "قيد التنفيذ",
        paymentStatus: "محجوزة",
        active: true,
        acceptanceCriteria: ["تسليم Wireframe واضح للصفحة", "تحديد أقسام الصفحة الرئيسية", "اعتماد الاتجاه البصري الأولي"],
        revisionLimit: "حد التعديلات: تعديلان",
        operationStatus: "بانتظار التسليم",
      },
      {
        number: "2",
        title: "المرحلة الثانية: تصميم الواجهة النهائية",
        amount: "$200",
        due: "بعد 7 أيام",
        status: "قادمة",
        paymentStatus: "بانتظار بدء المرحلة",
        acceptanceCriteria: [],
        revisionLimit: "",
        operationStatus: "لم تبدأ بعد",
      },
      {
        number: "3",
        title: "المرحلة الثالثة: التسليم النهائي",
        amount: "$100",
        due: "بعد 11 يوم",
        status: "قادمة",
        paymentStatus: "بانتظار بدء المرحلة",
        acceptanceCriteria: [],
        revisionLimit: "",
        operationStatus: "لم تبدأ بعد",
      },
    ],
    detailsLabel: "عرض التفاصيل",
    paymentsTitle: "حالة الدفعات",
    paymentsDescription: "كل مرحلة مرتبطة بدفعة لها حالة واضحة داخل النظام.",
    paymentSummary: [
      { label: "محجوز", value: "$150", tone: "reserved" },
      { label: "تحت المراجعة", value: "$0", tone: "review" },
      { label: "مصروف", value: "$0", tone: "released" },
      { label: "معلق", value: "$0", tone: "held" },
    ],
    paymentTableHeaders: ["المرحلة", "المبلغ", "الحالة", "التشغيل"],
    paymentRows: [
      { milestone: "المرحلة الأولى", amount: "$150", status: "محجوزة", operation: "بانتظار التسليم", tone: "reserved" },
      { milestone: "المرحلة الثانية", amount: "$200", status: "Waiting", operation: "لم تبدأ بعد", tone: "review" },
      { milestone: "المرحلة الثالثة", amount: "$100", status: "Waiting", operation: "لم تبدأ بعد", tone: "review" },
    ],
    activityTitle: "سجل الأحداث",
    activityDescription: "يوثق هذا السجل كل خطوة حدثت داخل الاتفاق.",
    activities: [
      { title: "تم إنشاء الاتفاق", description: "تم إنشاء مسودة الاتفاق بواسطة حمزة.", time: "منذ 3 أيام", tone: "violet" },
      { title: "تم توليد خطة الدفع بواسطة AI", description: "تم اقتراح 3 مراحل وسياسات اتفاق مبدئية.", time: "منذ 3 أيام", tone: "violet" },
      { title: "تم إرسال الدعوة للعميل", description: "تم إرسال رابط مراجعة الاتفاق إلى شركة المدار.", time: "منذ يومين", tone: "blue" },
      { title: "وافق العميل على الاتفاق", description: "أصبح الاتفاق نشطاً وبدأت المرحلة الأولى.", time: "منذ يوم", tone: "emerald" },
      { title: "تم تحديث موعد التسليم", description: "تم ضبط موعد تسليم المرحلة الأولى.", time: "منذ 6 ساعات", tone: "amber" },
      { title: "بانتظار تقديم تسليم", description: "المرحلة الأولى جاهزة الآن لإرفاق التسليم ومشاركته مع العميل.", time: "الآن", tone: "violet" },
    ],
    quickSummaryTitle: "ملخص سريع",
    quickSummaryItems: [
      { label: "قيمة الاتفاق", value: "$450", tone: "emerald" },
      { label: "عدد المراحل", value: "3", tone: "violet" },
      { label: "الحالة", value: "نشط", tone: "emerald" },
      { label: "آخر تحديث", value: "منذ ساعتين", tone: "amber" },
    ],
    financialSummaryTitle: "الملخص المالي",
    financialSummaryItems: [
      { label: "محجوز", value: "$150", tone: "reserved" },
      { label: "مصروف", value: "$0", tone: "released" },
      { label: "تحت المراجعة", value: "$0", tone: "review" },
      { label: "معلق", value: "$0", tone: "held" },
    ],
    quickActionsTitle: "إجراءات سريعة",
    quickActions: [{ label: "تقديم تسليم", active: true }, { label: "عرض بوابة العميل" }, { label: "نسخ رابط الدعوة" }, { label: "مراجعة السياسات" }],
    clientPortalTitle: "رابط العميل",
    clientPortalStatus: "متاح",
    clientPortalDescription: "يمكن للعميل متابعة الاتفاق والمراحل من الرابط التالي.",
    clientPortalLink: "/portal/dhmn-8K29",
    clientPortalAction: "فتح المعاينة",
    nextStepTitle: "الخطوة التالية",
    nextStepDescription: "ارفع ملفات المرحلة الأولى أو رابط المعاينة، ثم أرسلها للعميل للمراجعة والاعتماد.",
    nextStepAction: "تقديم تسليم الآن",
  },
  agreementDeliveryPage: {
    backLabel: "مساحة عمل الاتفاق",
    title: "تقديم تسليم المرحلة",
    subtitle: "أرفق رابط التسليم أو الملفات المطلوبة، ثم أرسلها للعميل لمراجعتها.",
    infoItems: [
      { label: "الاتفاق", value: "تصميم صفحة هبوط لشركة ناشئة" },
      { label: "العميل", value: "شركة المدار" },
      { label: "المرحلة", value: "المرحلة الأولى: الهيكل والتصميم الأولي" },
      { label: "الدفعة", value: "$150" },
      { label: "الموعد", value: "بعد يومين", icon: "calendar" },
    ],
    statusChips: ["قيد التنفيذ", "محجوزة", "بانتظار التسليم"],
    linkTitle: "رابط التسليم",
    linkTypes: [{ label: "Figma", active: true }, { label: "GitHub" }, { label: "Drive" }, { label: "Live Demo" }, { label: "Other" }],
    linkLabel: "رابط العمل أو التسليم",
    linkPlaceholder: "https://figma.com/file/...",
    linkHelp: "يمكنك إضافة رابط Figma، GitHub، Google Drive، Live Demo أو أي رابط قابل للمراجعة.",
    attachmentTitle: "إرفاق ملف اختياري",
    attachmentFileName: "landing-wireframe-v1.pdf",
    attachmentStatus: "جاهز للإرسال",
    summaryTitle: "وصف ما تم إنجازه",
    summaryLabel: "ملخص التسليم",
    summaryPlaceholder: "اكتب باختصار ما الذي أنجزته في هذه المرحلة، وما الذي يجب على العميل مراجعته...",
    summaryHelp: "الوصف الواضح يساعد العميل وAI لاحقاً على فهم نطاق التسليم.",
    notesTitle: "ملاحظات إضافية",
    notesOptional: "اختياري",
    notesLabel: "ملاحظات للعميل",
    notesPlaceholder: "مثال: يمكن للعميل التركيز على ترتيب الأقسام والرسالة الرئيسية في هذه المراجعة.",
    notesHelp: "اختياري - استخدمه لتوجيه العميل أثناء المراجعة.",
    confirmationTitle: "تأكيد قبل الإرسال",
    confirmationLabel: "أؤكد أن هذا التسليم يخص المرحلة المحددة ويلتزم بشروط القبول المتفق عليها.",
    confirmationWarning: "بعد الإرسال، ستنتقل الدفعة إلى مراجعة العميل ولا يمكن تعديل التسليم إلا بإرسال نسخة محدثة.",
    footerNote: "سيتم إشعار العميل، وتوثيق هذا الإرسال في سجل الأحداث.",
    cancelLabel: "إلغاء",
    draftLabel: "حفظ كمسودة",
    sendLabel: "إرسال التسليم للعميل",
    requirementsTitle: "شروط قبول المرحلة",
    requirements: [{ label: "تسليم Wireframe واضح للصفحة" }, { label: "تحديد أقسام الصفحة الرئيسية" }, { label: "اعتماد الاتجاه البصري الأولي" }],
    requirementsNote: "سيستخدم العميل هذه الشروط عند مراجعة التسليم.",
    checklistTitle: "قائمة التحقق",
    checklist: [
      { label: "رابط التسليم مضاف", done: true },
      { label: "وصف التسليم مكتوب", done: true },
      { label: "الملف (اختياري)" },
      { label: "شروط القبول واضحة", done: true },
      { label: "جاهز للإرسال للعميل" },
    ],
    afterSubmitTitle: "ماذا يحدث بعد الإرسال؟",
    afterSubmitItems: [
      { number: "1", label: "يتم إرسال إشعار للعميل" },
      { number: "2", label: "تنتقل الدفعة إلى Client Review" },
      { number: "3", label: "يراجع العميل التسليم" },
      { number: "4", label: "إما قبول وصرف أو طلب تعديل أو فتح AI Review" },
    ],
    paymentStatusTitle: "تحديث حالة الدفعة",
    paymentStatus: {
      beforeLabel: "قبل",
      beforeValue: "محجوزة",
      afterLabel: "بعد",
      afterValue: "Client Review",
      amount: "$150",
      note: "تبقى الدفعة محمية حتى يكتمل قرار المراجعة.",
    },
  },
} as const satisfies AgreementsContentMap;
