// AR: محتوى صفحة مراجعات الذكاء الاصطناعي الثابت.
// EN: Static content for the AI Review page.
import type { AIReviewContentMap } from "@/types";

export const aiReviewContent = {
  aiReview: {
    pageTitle: "مراجعات AI",
    pageDescription: "تابع الخلافات المفتوحة، توصيات الذكاء الاصطناعي، وأحوال الدفعات بسهولة.",
    exportLabel: "تصدير التقرير",
    searchPlaceholder: "ابحث باسم المشروع أو العميل أو المرحلة...",
    stats: [
      {
        key: "active",
        value: "4",
        label: "مراجعات مفتوحة",
        description: "تحتاج متابعة",
        status: "نشط",
      },
      {
        key: "pending",
        value: "1",
        label: "بانتظار التوصية",
        description: "AI يحلل التسليم والاعتراض",
        status: "تحليل",
      },
      {
        key: "outOfScope",
        value: "2",
        label: "طلبات خارج النطاق",
        description: "اعتراضات لا تطابق شروط القبول",
        status: "تنبيه",
      },
      {
        key: "frozen",
        value: "$570",
        label: "دفعات متأثرة",
        description: "تحت المراجعة أو التعليق",
        status: "مجمّد",
      },
    ],
    filterTabs: [
      { label: "الكل", count: 5 },
      { label: "تم الحل", count: 1 },
      { label: "خارج النطاق", count: 2 },
      { label: "توصية جاهزة", count: 2 },
      { label: "بانتظار AI", count: 1 },
      { label: "مفتوحة", count: 1 },
    ],
    filterDropdowns: [
      { key: "sort", label: "الأحدث أولًا" },
      { key: "time", label: "آخر 30 يوم" },
      { key: "paymentStatus", label: "كل حالات الدفعات" },
      { key: "aiRecommendation", label: "كل التوصيات" },
      { key: "agreements", label: "كل الاتفاقات" },
    ],
    tableHeaders: [
      "الإجراء",
      "آخر تحديث",
      "التطابق",
      "المبلغ",
      "حالة الدفعة",
      "نتيجة AI",
      "حالة المراجعة",
      "المرحلة / الاعتراض",
      "المشروع / العميل",
    ],
    rows: [
      {
        id: "1",
        projectName: "تصميم صفحة هبوط لشركة ناشئة",
        clientName: "شركة المدار",
        stage: "المرحلة الأولى: الهيكل والتصميم الأولي",
        objection: "العميل طلب تصميم باقي الصفحات ضمن نفس المرحلة.",
        reviewBadge: "توصية جاهزة",
        aiResult: "خارج النطاق",
        payStatus: "Ready to Release",
        amount: "$150",
        matchScore: 92,
        updatedAt: "منذ ساعة",
        actionLabel: "عرض المراجعة",
        showEyeIcon: true,
        detail: {
          aiAnalysis: "شروط قبول المرحلة تذكر Wireframe وتحديد أقسام الصفحة الرئيسية فقط، مما يعني أن طلب تصميم باقي الصفحات يعد خارج النطاق.",
          fulfilledCriteria: [
            { text: "تسليم Wireframe واضح للصفحة", fulfilled: true },
            { text: "تحديد أقسام الصفحة الرئيسية", fulfilled: true },
            { text: "اعتماد الاتجاه البصري الأولي", fulfilled: true },
          ],
          outOfScopeNote: "خارج النطاق: تصميم باقي الصفحات",
          paymentRecommendation: "صرف الدفعة أو إنشاء Change Request للصفحات الإضافية",
          paymentRecommendationText: "يوصي ضمان بصرف دفعة المرحلة الأولى أو إنشاء Change Request منفصل للصفحات الإضافية.",
          reviewTitle: "مراجعة تسليم المرحلة الأولى",
          reviewDescription: "تصميم صفحة هبوط لشركة ناشئة — شركة المدار",
          aiNote: "تم تحليل الاعتراض بناءً على شروط قبول المرحلة، التسليم المرفوع، وبيانات الاتفاقية.",
          badges: [
            { label: "Ready to Release", tone: "success" },
            { label: "خارج النطاق", tone: "red" },
            { label: "توصية جاهزة", tone: "purple" },
          ],
          agreementValue: "اتفاق تصميم صفحة هبوط",
          stageValue: "المرحلة الأولى: الهيكل والتصميم الأولي",
          amountValue: "$150",
          openedValue: "منذ 4 ساعات",
          updatedValue: "منذ ساعة",
          confidenceScore: 92,
          confidenceLabel: "ثقة عالية",
          recommendationTitle: "الاعتراض خارج نطاق المرحلة",
          recommendationSummary: "يوصي ضمان بصرف دفعة المرحلة الأولى أو إنشاء Change Request منفصل.",
          recommendationDetail: "شروط المرحلة تركز على تسليم Wireframe وتحديد أقسام الصفحة الرئيسية فقط. الطلب الإضافي لتصميم باقي الصفحات خارج نطاق هذه المرحلة.",
          objectionQuote: "\"التسليم غير كافٍ لأننا نحتاج أيضًا تصميم باقي الصفحات الداخلية.\"",
          objectionType: "طلب خارج نطاق المرحلة",
          relatedCriterionLabel: "شرط القبول المرتبط",
          relatedCriterionValue: "غير مرتبط مباشرة بأي شرط قبول محدد",
          objectionAINote: "الاعتراض يجب أن يكون مرتبطًا بشرط قبول محدد حتى يؤثر على صرف الدفعة.",
          stageTermsDetails: {
            stageName: "المرحلة الأولى: الهيكل والتصميم الأولي",
            amount: "$150",
            duration: "خلال 5 أيام",
            amendments: "تعديلان",
          },
          outOfScopeStageNote: "هذه المرحلة لا تشمل تصميم الصفحات الداخلية أو النسخ النهائي.",
          paymentReleaseNote: "تصبح الدفعة قابلة للصرف عند تحقق شروط القبول أو عند اعتماد التوصية.",
          deliverableUploader: "حمزة",
          deliverableUploadTime: "منذ 5 ساعات",
          deliverableStatusLabel: "تم الإرسال للمراجعة",
          deliverableDescription: "تم تجهيز الهيكل الأولي للصفحة، تحديد أقسام Hero والعملاء والاتجاه البصري.",
          deliverableFiles: [
            { name: "Figma Wireframe", description: "figma.com/file/dhaman-landing-wireframe", type: "link" },
            { name: "landing-wireframe-v1.pdf", description: "ملف PDF مرفق", type: "file" },
          ],
          criteriaAnalysisDescription: "يقارن AI بين شروط القبول، التسليم المرفوع، واعتراض العميل لتحديد حالة كل شرط.",
          criteriaAnalysis: [
            { criterion: "تسليم Wireframe واضح للصفحة", evidence: "رابط Figma والملف المرفق يحتويان على Wireframe للصفحة الرئيسية.", status: "مكتمل" },
            { criterion: "تحديد أقسام الصفحة الرئيسية", evidence: "تم تحديد أقسام Hero، المزايا، طريقة العمل، والدعوة للعمل.", status: "مكتمل" },
            { criterion: "اعتماد الاتجاه البصري الأولي", evidence: "يوجد اتجاه بصري مبدئي، لكن قد يحتاج العميل إلى تعليقات إضافية.", status: "مكتمل جزئيًا" },
            { criterion: "تصميم باقي الصفحات", evidence: "غير مذكور في شروط قبول المرحلة الأولى.", status: "خارج النطاق" },
          ],
          reasonExplanation: "بناءً على شروط قبول المرحلة الأولى، فإن المطلوب كان تسليم Wireframe وتحديد أقسام الصفحة الرئيسية فقط. طلب الصفحات الإضافية يخرج عن نطاق هذه المرحلة.",
          reasonPoints: [
            "شروط القبول لا تذكر الصفحات الداخلية.",
            "التسليم يحتوي على Wireframe للصفحة الرئيسية.",
            "طلب الصفحات الإضافية يجب تحويله إلى Change Request منفصل.",
          ],
          suggestedActions: [
            { title: "إرسال توضيح للعميل", description: "مشاركة ملخص التوصية وشرح لماذا الطلب خارج نطاق المرحلة.", buttonLabel: "نسخ ملخص للعميل" },
            { title: "إنشاء Change Request", description: "تحويل طلب الصفحات الإضافية إلى طلب منفصل بتكلفة وم_DURATION جديدة.", buttonLabel: "إنشاء طلب تغيير" },
            { title: "صرف دفعة المرحلة", description: "اعتماد التوصية وجعل الدفعة جاهزة للصرف للفريلانسر.", buttonLabel: "اعتماد الصرف" },
          ],
        },
      },
      {
        id: "2",
        projectName: "كتابة محتوى صفحة بيع",
        clientName: "شركة نمو",
        stage: "المرحلة الأولى: نسخة أولية",
        objection: "العميل يرى أن النص لا يطابق النبرة المطلوبة.",
        reviewBadge: "بانتظار AI",
        aiResult: "قيد التحليل",
        payStatus: "AI Review",
        amount: "$120",
        matchScore: null,
        updatedAt: "منذ 3 ساعات",
        actionLabel: "متابعة الحالة",
        showEyeIcon: true,
        detail: {
          aiAnalysis: "جاري تحليل مدى تطابق المحتوى مع شروط القبول المعرفة في الاتفاقية.",
          fulfilledCriteria: [
            { text: "تسليم النص الأولي للصفحة", fulfilled: true },
            { text: "مراجعة النبرة الصوتية للعلامة التجارية", fulfilled: false },
          ],
          outOfScopeNote: "قيد التحليل: لم يتم تحديد نتيجة بعد.",
          paymentRecommendation: "بانتظار نتيجة التحليل",
          paymentRecommendationText: "سيتم تحديث توصية الدفعة بمجرد اكتمال التحليل.",
          reviewTitle: "مراجعة تسليم النص الأولي",
          reviewDescription: "كتابة محتوى صفحة بيع — شركة نمو",
          aiNote: "جاري تحليل مدى تطابق المحتوى مع شروط القبول والنبرة المطلوبة.",
          badges: [
            { label: "AI Review", tone: "purple" },
            { label: "قيد التحليل", tone: "cyan" },
          ],
          agreementValue: "اتفاق كتابة محتوى",
          stageValue: "المرحلة الأولى: نسخة أولية",
          amountValue: "$120",
          openedValue: "منذ 5 ساعات",
          updatedValue: "منذ 3 ساعات",
          confidenceScore: 0,
          confidenceLabel: "جاري التحليل",
          recommendationTitle: "جاري التحليل",
          recommendationSummary: "لم يتم إنشاء توصية بعد — التحليل لا يزال قيد التنفيذ.",
          recommendationDetail: "يتم حاليًا تحليل التسليم المرفوع ومقارنته بشروط القبول.",
          objectionQuote: "\"النص لا يعكس نبرة العلامة التجارية التي اتفقنا عليها.\"",
          objectionType: "عدم تطابق النبرة",
          relatedCriterionLabel: "شرط القبول المرتبط",
          relatedCriterionValue: "مراجعة النبرة الصوتية للعلامة التجارية",
          objectionAINote: "سيتم الربط آليًا بشرط القبول الأقرب بعد اكتمال التحليل.",
          stageTermsDetails: {
            stageName: "المرحلة الأولى: نسخة أولية",
            amount: "$120",
            duration: "خلال 7 أيام",
            amendments: "تعديل واحد",
          },
          outOfScopeStageNote: "المرحلة لا تشمل إعادة كتابة كاملة للنص.",
          paymentReleaseNote: "سيتم تحديث توصية الدفعة بعد اكتمال التحليل.",
          deliverableUploader: "سارة",
          deliverableUploadTime: "منذ 6 ساعات",
          deliverableStatusLabel: "بانتظار المراجعة",
          deliverableDescription: "تسليم النص الأولي لصفحة البيع مع المسودة المرفقة.",
          deliverableFiles: [
            { name: "نسخة أولية - صفحة البيع", description: "docs.google.com/document/d/sale-page-copy", type: "link" },
            { name: "sale-page-v1.pdf", description: "ملف PDF مرفق", type: "file" },
          ],
          criteriaAnalysisDescription: "يقارن AI بين شروط القبول، التسليم المرفوع، واعتراض العميل لتحديد حالة كل شرط.",
          criteriaAnalysis: [
            { criterion: "تسليم النص الأولي للصفحة", evidence: "تم رفع النص الأولي عبر رابط المستند.", status: "مكتمل" },
            { criterion: "مراجعة النبرة الصوتية للعلامة التجارية", evidence: "جاري التحقق من توافق النبرة مع دليل العلامة التجارية.", status: "مكتمل جزئيًا" },
          ],
          reasonExplanation: "لم يتم إنشاء توصية بعد — التحليل لا يزال قيد التنفيذ وسيتم تقديم التوصية بعد الاكتمال.",
          reasonPoints: [
            "جاري تحليل تطابق المحتوى مع شروط القبول.",
            "سيتم تقديم التوصية تلقائيًا بعد اكتمال التحليل.",
          ],
          suggestedActions: [
            { title: "انتظار نتيجة التحليل", description: "انتظر حتى يكمل AI تحليل التسليم والاعتراض.", buttonLabel: "متابعة الحالة" },
          ],
        },
      },
      {
        id: "3",
        projectName: "هوية بصرية لمتجر إلكتروني",
        clientName: "متجر نوفا",
        stage: "المرحلة الثانية: النماذج النهائية",
        objection: "الألوان لا تناسب الهوية المطلوبة.",
        reviewBadge: "توصية جاهزة",
        aiResult: "تعديل مطلوب",
        payStatus: "On Hold",
        amount: "$300",
        matchScore: 64,
        updatedAt: "منذ 6 ساعات",
        actionLabel: "عرض المراجعة",
        showEyeIcon: true,
        detail: {
          aiAnalysis: "بعض العناصر البصرية لا تتطابق مع شروط القبول المحددة.",
          fulfilledCriteria: [
            { text: "تسليم الشعار بخلفيات متعددة", fulfilled: true },
            { text: "توافق الألوان مع دليل الهوية", fulfilled: false },
            { text: "تسليم ملفات المصدر المفتوحة", fulfilled: true },
          ],
          outOfScopeNote: "تعديل مطلوب على الألوان والنماذج النهائية.",
          paymentRecommendation: "تعليق الدفعة حتى اكتمال التعديلات",
          paymentRecommendationText: "يُوصى بتعليق الدفعة حتى يقدم المقاول التعديلات المطلوبة.",
          reviewTitle: "مراجعة تسليم النماذج النهائية",
          reviewDescription: "هوية بصرية لمتجر إلكتروني — متجر نوفا",
          aiNote: "تم تحليل التسليم والاعتراض بناءً على شروط قبول المرحلة الثانية.",
          badges: [
            { label: "On Hold", tone: "amber" },
            { label: "تعديل مطلوب", tone: "amber" },
            { label: "توصية جاهزة", tone: "purple" },
          ],
          agreementValue: "اتفاق هوية بصرية",
          stageValue: "المرحلة الثانية: النماذج النهائية",
          amountValue: "$300",
          openedValue: "منذ يوم",
          updatedValue: "منذ 6 ساعات",
          confidenceScore: 64,
          confidenceLabel: "ثقة متوسطة",
          recommendationTitle: "تعديل مطلوب على الألوان والنماذج",
          recommendationSummary: "يوصى بتعليق الدفعة حتى يقدم المقاول التعديلات المطلوبة على الألوان.",
          recommendationDetail: "شروط القبول تتطلب توافق الألوان مع دليل الهوية، لكن التسليم لا يحقق هذا الشرط بالكامل.",
          objectionQuote: "\"الألوان المختارة لا تناسب الهوية البصرية التي حددناها مسبقًا.\"",
          objectionType: "عدم تطابق بصري",
          relatedCriterionLabel: "شرط القبول المرتبط",
          relatedCriterionValue: "توافق الألوان مع دليل الهوية",
          objectionAINote: "الاعتراض مرتبط بشرط قبول محدد — توافق الألوان مع دليل الهوية غير محقق بعد.",
          stageTermsDetails: {
            stageName: "المرحلة الثانية: النماذج النهائية",
            amount: "$300",
            duration: "خلال 10 أيام",
            amendments: "3 تعديلات",
          },
          outOfScopeStageNote: "المرحلة تتطلب توافق الألوان مع دليل الهوية كشرط أساسي.",
          paymentReleaseNote: "تصبح الدفعة قابلة للصرف بعد تحقق شرط توافق الألوان.",
          deliverableUploader: "أحمد",
          deliverableUploadTime: "منذ يومين",
          deliverableStatusLabel: "بانتظار المراجعة",
          deliverableDescription: "تسليم النماذج النهائية للهوية البصرية مع ملفات المصدر.",
          deliverableFiles: [
            { name: "Brand Identity Final", description: "figma.com/file/nova-brand-identity", type: "link" },
            { name: "nova-brand-assets-v2.zip", description: "ملف مضغوط مرفق", type: "file" },
          ],
          criteriaAnalysisDescription: "يقارن AI بين شروط القبول، التسليم المرفوع، واعتراض العميل لتحديد حالة كل شرط.",
          criteriaAnalysis: [
            { criterion: "تسليم الشعار بخلفيات متعددة", evidence: "تم رفع الشعار بخلفيات متنوعة.", status: "مكتمل" },
            { criterion: "توافق الألوان مع دليل الهوية", evidence: "الألوان لا تتطابق بالكامل مع دليل الهوية المحدد.", status: "مكتمل جزئيًا" },
            { criterion: "تسليم ملفات المصدر المفتوحة", evidence: "ملفات المصدر مرفقة بصيغ متعددة.", status: "مكتمل" },
          ],
          reasonExplanation: "شروط القبول تتطلب توافق الألوان مع دليل الهوية، لكن التسليم لا يحقق هذا الشرط بالكامل. يُوصى بتعليق الدفعة.",
          reasonPoints: [
            "الألوان المختارة لا تتطابق مع دليل الهوية المتفق عليه.",
            "باقي المعايير محققة (الشعار وملفات المصدر).",
            "يتعين على المقاول تعديل الألوان قبل صرف الدفعة.",
          ],
          suggestedActions: [
            { title: "إرسال توضيح للعميل", description: "مشاركة ملخص التوصية وشرح سبب تعليق الدفعة.", buttonLabel: "نسخ ملخص للعميل" },
            { title: "طلب تعديل", description: "إرسال طلب تعديل على الألوان والنماذج النهائية.", buttonLabel: "طلب تعديل" },
            { title: "تعليق الدفعة", description: "تعليق الدفعة حتى يتم تقديم التعديلات المطلوبة.", buttonLabel: "تعليق الدفعة" },
          ],
        },
      },
      {
        id: "4",
        projectName: "تطوير موقع تعريفي",
        clientName: "شركة روافد",
        stage: "المرحلة الأولى: الصفحة الرئيسية",
        objection: "العميل طلب إضافة نظام تسجيل دخول.",
        reviewBadge: "تم الحل",
        aiResult: "طلب إضافي",
        payStatus: "Released",
        amount: "$250",
        matchScore: 88,
        updatedAt: "أمس",
        actionLabel: "عرض النتيجة",
        showEyeIcon: true,
        detail: {
          aiAnalysis: "تم حل الاعتراض — طلب إضافة نظام تسجيل دخول يُعد طلبًا إضافيًا خارج نطاق المرحلة.",
          fulfilledCriteria: [
            { text: "تسليم الصفحة الرئيسية كاملة", fulfilled: true },
            { text: "توافق التصميم مع المتطلبات الأولية", fulfilled: true },
          ],
          outOfScopeNote: "طلب إضافي: نظام تسجيل الدخول خارج نطاق المرحلة الحالية.",
          paymentRecommendation: "تم صرف الدفعة",
          paymentRecommendationText: "تم صرف الدفعة بعد تأكيد اكتمال التسليم.",
          reviewTitle: "مراجعة تسليم الصفحة الرئيسية",
          reviewDescription: "تطوير موقع تعريفي — شركة روافد",
          aiNote: "تم حل الاعتراض — الطلب خارج نطاق المرحلة ويحتاج اتفاقية منفصلة.",
          badges: [
            { label: "Released", tone: "blue" },
            { label: "طلب إضافي", tone: "blue" },
            { label: "تم الحل", tone: "success" },
          ],
          agreementValue: "اتفاق تطوير موقع",
          stageValue: "المرحلة الأولى: الصفحة الرئيسية",
          amountValue: "$250",
          openedValue: "منذ 3 أيام",
          updatedValue: "أمس",
          confidenceScore: 88,
          confidenceLabel: "ثقة عالية",
          recommendationTitle: "الاعتراض خارج نطاق المرحلة — تم الحل",
          recommendationSummary: "تم صرف الدفعة بعد تأكيد اكتمال التسليم.",
          recommendationDetail: "جميع شروط القبول محققة. الطلب الإضافي لنظام تسجيل الدخول يتطلب اتفاقية منفصلة.",
          objectionQuote: "\"نحتاج نظام تسجيل دخول ضمن نفس المشروع.\"",
          objectionType: "طلب إضافي خارج النطاق",
          relatedCriterionLabel: "شرط القبول المرتبط",
          relatedCriterionValue: "غير مرتبط — الطلب خارج نطاق المرحلة",
          objectionAINote: "الطلب الإضافي تم توثيقه ويمكن تحويله إلى اتفاقية منفصلة.",
          stageTermsDetails: {
            stageName: "المرحلة الأولى: الصفحة الرئيسية",
            amount: "$250",
            duration: "خلال 7 أيام",
            amendments: "تعديل واحد",
          },
          outOfScopeStageNote: "المرحلة تشمل الصفحة الرئيسية فقط — نظام تسجيل الدخول يتطلب مرحلة إضافية.",
          paymentReleaseNote: "تم صرف الدفعة بعد تأكيد اكتمال جميع شروط القبول.",
          deliverableUploader: "خالد",
          deliverableUploadTime: "منذ 3 أيام",
          deliverableStatusLabel: "تم المراجعة",
          deliverableDescription: "تسليم الصفحة الرئيسية الكاملة مع التصميم المتجاوب.",
          deliverableFiles: [
            { name: "الصفحة الرئيسية", description: "figma.com/file/rawafid-landing", type: "link" },
            { name: "rawafid-homepage-v1.pdf", description: "ملف PDF مرفق", type: "file" },
          ],
          criteriaAnalysisDescription: "يقارن AI بين شروط القبول، التسليم المرفوع، واعتراض العميل لتحديد حالة كل شرط.",
          criteriaAnalysis: [
            { criterion: "تسليم الصفحة الرئيسية كاملة", evidence: "تم رفع التصميم النهائي للصفحة الرئيسية.", status: "مكتمل" },
            { criterion: "توافق التصميم مع المتطلبات الأولية", evidence: "التصميم يتطابق مع المتطلبات الأولية المتفق عليها.", status: "مكتمل" },
          ],
          reasonExplanation: "جميع شروط القبول محققة. الطلب الإضافي لنظام تسجيل الدخول يجب تحويله إلى اتفاقية منفصلة.",
          reasonPoints: [
            "شروط القبول محققة بالكامل.",
            "التسليم يطابق المتطلبات المتفق عليها.",
            "نظام تسجيل الدخول يُعد طلبًا إضافيًا ويحتاج مرحلة منفصلة.",
          ],
          suggestedActions: [
            { title: "صرف دفعة المرحلة", description: "اعتماد التوصية وصرف الدفعة للفريلانسر.", buttonLabel: "اعتماد الصرف" },
            { title: "إنشاء اتفاقية إضافية", description: "تحويل طلب نظام تسجيل الدخول إلى اتفاقية منفصلة.", buttonLabel: "إنشاء اتفاقية" },
          ],
        },
      },
      {
        id: "5",
        projectName: "تصميم لوحة تحكم SaaS",
        clientName: "منصة بيان",
        stage: "المرحلة الثالثة: التصميم النهائي",
        objection: "بعض الشاشات غير مكتملة حسب شروط القبول.",
        reviewBadge: "مفتوحة",
        aiResult: "بانتظار بدء المراجعة",
        payStatus: "AI Review",
        amount: "$400",
        matchScore: null,
        updatedAt: "منذ يومين",
        actionLabel: "بدء المراجعة",
        showEyeIcon: true,
        detail: {
          aiAnalysis: "بانتظار بدء المراجعة — لم يتم تحليل التسليم بعد.",
          fulfilledCriteria: [
            { text: "تسليم جميع شاشات لوحة التحكم", fulfilled: false },
            { text: "توافق التصميم مع دليل النمط", fulfilled: false },
          ],
          outOfScopeNote: "لم يتم تحديد نتيجة بعد.",
          paymentRecommendation: "بانتظار بدء المراجعة",
          paymentRecommendationText: "سيتم تقديم التوصية بعد اكتمال التحليل.",
          reviewTitle: "بانتظار بدء المراجعة",
          reviewDescription: "تصميم لوحة تحكم SaaS — منصة بيان",
          aiNote: "لم يتم بدء التحليل بعد — ستبدأ المراجعة تلقائيًا بعد رفع التسليم.",
          badges: [
            { label: "AI Review", tone: "purple" },
            { label: "بانتظار بدء المراجعة", tone: "muted" },
          ],
          agreementValue: "اتفاق تصميم لوحة تحكم",
          stageValue: "المرحلة الثالثة: التصميم النهائي",
          amountValue: "$400",
          openedValue: "منذ 3 أيام",
          updatedValue: "منذ يومين",
          confidenceScore: 0,
          confidenceLabel: "بانتظار التحليل",
          recommendationTitle: "بانتظار بدء المراجعة",
          recommendationSummary: "لم يتم إنشاء توصية بعد — المراجعة لم تبدأ.",
          recommendationDetail: "سيتم تقديم التوصية تلقائيًا بعد بدء المراجعة وتحليل التسليم.",
          objectionQuote: "\"بعض الشاشات غير مكتملة حسب شروط القبول.\"",
          objectionType: "بانتظار التحليل",
          relatedCriterionLabel: "شرط القبول المرتبط",
          relatedCriterionValue: "سيتم التحديد بعد بدء المراجعة",
          objectionAINote: "لم يتم ربط الاعتراض بشرط قبول بعد — سيتم تلقائيًا بعد بدء التحليل.",
          stageTermsDetails: {
            stageName: "المرحلة الثالثة: التصميم النهائي",
            amount: "$400",
            duration: "خلال 14 يومًا",
            amendments: "تعديلان",
          },
          outOfScopeStageNote: "المرحلة تتطلب تسليم جميع شاشات لوحة التحكم الكاملة.",
          paymentReleaseNote: "تصبح الدفعة قابلة للصرف بعد تحقق جميع شروط القبول.",
          deliverableUploader: "ليلى",
          deliverableUploadTime: "منذ 4 أيام",
          deliverableStatusLabel: "بانتظار الرفع",
          deliverableDescription: "بانتظار رفع التسليم النهائي لجميع شاشات لوحة التحكم.",
          deliverableFiles: [],
          criteriaAnalysisDescription: "يقارن AI بين شروط القبول، التسليم المرفوع، واعتراض العميل لتحديد حالة كل شرط.",
          criteriaAnalysis: [
            { criterion: "تسليم جميع شاشات لوحة التحكم", evidence: "لم يتم رفع التسليم بعد.", status: "مكتمل جزئيًا" },
            { criterion: "توافق التصميم مع دليل النمط", evidence: "بانتظار المراجعة.", status: "مكتمل جزئيًا" },
          ],
          reasonExplanation: "لم يتم بدء المراجعة بعد — سيتم تقديم التوصية بعد تحليل التسليم.",
          reasonPoints: [
            "لم يتم رفع التسليم الكامل بعد.",
            "بانتظار بدء التحليل.",
          ],
          suggestedActions: [
            { title: "بدء المراجعة", description: "بدء مراجعة التسليم وتحليل شروط القبول.", buttonLabel: "بدء المراجعة" },
          ],
        },
      },
    ],
  },
  detailPage: {
    backButtonLabel: "العودة لمراجعات AI",
    pageTitle: "تفاصيل مراجعة AI",
    pageDescription: "راجع تحليل الذكاء الاصطناعي للتسليم، الاعتراض، وشروط القبول.",
    approveRecommendationLabel: "اعتماد التوصية",
    openWorkspaceLabel: "فتح مساحة العمل",
    copySummaryLabel: "نسخ ملخص التوصية",
    aiRecommendationLabel: "توصية AI",
    clientObjectionLabel: "اعتراض العميل",
    stageTermsLabel: "شروط المرحلة المتفق عليها",
    uploadedDeliverableLabel: "التسليم المرفوع",
    uploadedByLabel: "رُفع بواسطة",
    uploadTimeLabel: "وقت الرفع",
    criteriaAnalysisLabel: "تحليل شروط القبول",
    reasonLabel: "سبب التوصية",
    suggestedActionsLabel: "الإجراءات المقترحة",
    openLinkLabel: "فتح الرابط",
    downloadLabel: "تحميل",
    copyDeliverableLinkLabel: "نسخ رابط التسليم",
    downloadFileLabel: "تحميل الملف",
    openDeliverableLinkLabel: "فتح رابط التسليم",
    createChangeRequestLabel: "إنشاء Change Request",
    shareSummaryLabel: "مشاركة الملخص مع العميل",
    createChangeRequestShortLabel: "إنشاء طلب تغيير",
    acceptRecommendationShortLabel: "اعتماد التوصية",
    stageNameLabel: "اسم المرحلة",
    amountLabel: "المبلغ",
    durationLabel: "المدة",
    amendmentsLabel: "التعديلات",
    acceptanceCriteriaLabel: "شروط القبول",
    criterionLabel: "الشرط",
    evidenceLabel: "الدليل",
    statusLabel: "الحالة",
    objectionTypeLabel: "نوع الاعتراض",
    relatedCriterionLabel: "شرط القبول المرتبط",
  },
} as const satisfies AIReviewContentMap;