// AR: محتوى صفحة العملاء الثابت.
// EN: Static content for the Clients page.
import type { ClientContentMap } from "@/types";

export const clientContent = {
  clients: {
    pageTitle: "العملاء",
    pageDescription: "تابع عملاءك، الاتفاقات المرتبطة بهم، وحالة الدفعات بسهولة.",
    addClientLabel: "إضافة عميل",
    exportLabel: "تصدير العملاء",
    searchPlaceholder: "ابحث باسم العميل أو البريد الإلكتروني...",
    stats: [
      {
        key: "total",
        value: "12",
        label: "إجمالي العملاء",
        description: "عميل مرتبط باتفاق واحد أو أكثر",
        trend: "+2 هذا الشهر",
      },
      {
        key: "active",
        value: "6",
        label: "عملاء نشطون",
        description: "لديهم اتفاقات قيد التنفيذ",
        trend: "من إجمالي 12",
      },
      {
        key: "pendingAction",
        value: "3",
        label: "بانتظار إجراء",
        description: "مراجعة تسليم أو طلب تعديل",
        trend: "يحتاج انتباهًا",
      },
      {
        key: "totalValue",
        value: "$4,820",
        label: "قيمة الاتفاقات",
        description: "إجمالي الاتفاقات المرتبطة",
        trend: "كل الاتفاقات",
      },
    ],
    filterTabs: [
      { label: "الكل", count: 5 },
      { label: "مكتملون", count: 1 },
      { label: "لديهم مراجعات AI", count: 1 },
      { label: "بانتظار إجراء", count: 2 },
      { label: "نشطون", count: 1 },
    ],
    filterDropdowns: [
      { key: "sort", label: "الأحدث نشاطًا" },
      { key: "time", label: "آخر 90 يوم" },
      { key: "paymentStatus", label: "كل حالات الدفعات" },
      { key: "agreementStatus", label: "كل حالات الاتفاق" },
    ],
    tableHeaders: [
      "العميل",
      "الاتفاقات",
      "القيمة",
      "الحالة",
      "إجراء مطلوب",
      "آخر نشاط",
      "الإجراء",
    ],
    rows: [
      {
        id: "1",
        name: "شركة المدار",
        email: "client@almadar.com",
        avatarInitial: "م",
        agreementCount: 1,
        agreementLabel: "1 اتفاق",
        latestAgreement: "تصميم صفحة هبوط لشركة ناشئة",
        totalValue: "$450",
        status: "نشط",
        statusBadge: "نشط",
        portalActive: true,
        actionBadge: "بانتظار مراجعة تسليم",
        lastActivity: "منذ ساعتين",
      },
      {
        id: "2",
        name: "متجر نوفا",
        email: "hello@nova-store.com",
        avatarInitial: "ن",
        agreementCount: 2,
        agreementLabel: "2 اتفاقات",
        latestAgreement: "هوية بصرية لمتجر إلكتروني",
        totalValue: "$900",
        status: "يحتاج متابعة",
        statusBadge: "يحتاج متابعة",
        portalActive: true,
        actionBadge: "طلب تعديل مفتوح",
        lastActivity: "منذ 5 ساعات",
      },
      {
        id: "3",
        name: "شركة روافد",
        email: "projects@rawafed.com",
        avatarInitial: "ر",
        agreementCount: 1,
        agreementLabel: "1 اتفاق",
        latestAgreement: "تطوير موقع تعريفي",
        totalValue: "$750",
        status: "مكتمل",
        statusBadge: "مكتمل",
        portalActive: true,
        actionBadge: "لا يوجد",
        lastActivity: "أمس",
      },
      {
        id: "4",
        name: "منصة بيان",
        email: "team@bayan.app",
        avatarInitial: "ب",
        agreementCount: 1,
        agreementLabel: "1 اتفاق",
        latestAgreement: "تصميم لوحة تحكم SaaS",
        totalValue: "$1,200",
        status: "نشط",
        statusBadge: "نشط",
        portalActive: true,
        actionBadge: "مراجعة AI مفتوحة",
        lastActivity: "منذ يومين",
      },
      {
        id: "5",
        name: "شركة نمو",
        email: "content@nomo.co",
        avatarInitial: "و",
        agreementCount: 3,
        agreementLabel: "3 اتفاقات",
        latestAgreement: "كتابة محتوى صفحة بيع",
        totalValue: "$620",
        status: "نشط",
        statusBadge: "نشط",
        portalActive: true,
        actionBadge: "بانتظار AI",
        lastActivity: "منذ 3 أيام",
      },
    ],
  },
} as const satisfies ClientContentMap;