import type { DeliveryStatus, DeliveriesContent } from "@/types";

// AR: ملصقات الفلاتر العربية لحالات التسليم المستخدمة في الشريط العلوي.
// EN: Arabic filter labels for delivery statuses used in the filter bar.
export const deliveryStatusLabelMap: Record<DeliveryStatus, string> = {
  DRAFT: "مسودة",
  SUBMITTED: "تم الإرسال",
  CLIENT_REVIEW: "تحت مراجعة العميل",
  CHANGES_REQUESTED: "طلب تعديل",
  ACCEPTED: "مقبولة",
  DISPUTED: "نزاع",
};

// AR: الحالة الافتراضية لعرض حالة غير معروفة.
// EN: Default label for unknown statuses.
export const deliveryStatusFallbackLabel = "غير معروف";

// AR: فلاتر الحالات كقائمة ثابتة بالقيم والأسماء العربية.
// EN: Status filter options as a static array of values and Arabic labels.
export const deliveryStatusFilterOptions: { value: DeliveryStatus; label: string }[] = [
  { value: "DRAFT", label: "مسودة" },
  { value: "SUBMITTED", label: "تم الإرسال" },
  { value: "CLIENT_REVIEW", label: "تحت مراجعة العميل" },
  { value: "CHANGES_REQUESTED", label: "طلب تعديل" },
  { value: "ACCEPTED", label: "مقبولة" },
  { value: "DISPUTED", label: "نزاع" },
];

// AR: نصوص واجهة التسليمات — عناوين، تلميحات، رسائل فارغة، أخطاء.
// EN: Deliveries UI strings — titles, placeholders, empty states, errors.
export const deliveriesUiStrings = {
  pageTitle: "التسليمات",
  pageSubtitle: "تابع كل تسليمات المراحل، مراجعات العملاء، وحالة الدفعات المرتبطة بها.",
  searchPlaceholder: "ابحث باسم المشروع أو العميل...",
  exportLabel: "تصدير التقرير",
  createLabel: "تقديم تسليم جديد",
  emptyTitle: "لا توجد تسليمات",
  emptyMessage: "لم يتم العثور على تسليمات تطابق الفلاتر الحالية.",
  errorTitle: "خطأ في تحميل التسليمات",
  errorRetry: "حاول مرة أخرى",
  loadingText: "جارٍ التحميل...",
  viewLabel: "عرض التفاصيل",
  editLabel: "تعديل",
  submitLabel: "إرسال للمراجعة",
  paginationPrevious: "السابق",
  paginationNext: "التالي",
  paginationPage: "صفحة",
  paginationOf: "من",
} as const;

export const deliveriesContent = {
  title: "التسليمات",
  subtitle: "تابع كل تسليمات المراحل، مراجعات العملاء، وحالة الدفعات المرتبطة بها.",
  searchPlaceholder: "ابحث باسم المشروع أو العميل...",
  exportLabel: "تصدير التقرير",
  createLabel: "تقديم تسليم جديد",
  metrics: [
    { label: "بانتظار التسليم", value: "3", helper: "مراحل جاهزة للتسليم", badge: "انتباه", tone: "amber" as const },
    { label: "تحت مراجعة العميل", value: "2", helper: "تسليمات تم إرسالها", badge: "نشط", tone: "violet" as const },
    { label: "مقبولة", value: "5", helper: "دفعات جاهزة أو مصروفة", badge: "مكتمل", tone: "emerald" as const },
    { label: "تحتاج إجراء", value: "1", helper: "طلب تعديل أو اعتراض", badge: "عاجل", tone: "red" as const },
  ],
  filters: [
    { label: "الكل", count: "5", active: true },
    { label: "بانتظار التسليم", count: "3" },
    { label: "تحت مراجعة العميل", count: "2" },
    { label: "مقبولة", count: "5" },
    { label: "طلب تعديل", count: "1" },
    { label: "AI Review", count: "1" },
  ],
  sortFilters: ["كل الاتفاقات", "كل العملاء", "آخر 30 يوم", "الأحدث أولاً"],
  tableHeaders: ["المشروع / العميل", "المرحلة", "التسليم", "حالة التسليم", "حالة الدفعة", "المبلغ", "آخر تحديث", "الإجراء"],
  deliveries: [
    {
      id: "delivery-001",
      project: "تصميم صفحة هبوط لشركة ناشئة",
      client: "شركة المدار",
      milestone: "المرحلة الأولى: الهيكل والتصميم الأولي",
      delivery: "رابط Figma",
      deliveryStatus: "تحت مراجعة العميل",
      deliveryTone: "review" as const,
      paymentStatus: "Client Review",
      paymentTone: "client" as const,
      amount: "$150",
      lastUpdate: "منذ ساعتين",
      actionLabel: "عرض التسليم",
      active: true,
    },
    {
      id: "delivery-002",
      project: "هوية بصرية لمتجر إلكتروني",
      client: "متجر نوفا",
      milestone: "المرحلة الثانية: النماذج النهائية",
      delivery: "ZIP + Drive",
      deliveryStatus: "طلب تعديل",
      deliveryTone: "change" as const,
      paymentStatus: "On Hold",
      paymentTone: "hold" as const,
      amount: "$300",
      lastUpdate: "منذ 5 ساعات",
      actionLabel: "مراجعة طلب التعديل",
    },
    {
      id: "delivery-003",
      project: "تطوير موقع تعريفي",
      client: "شركة روافد",
      milestone: "المرحلة الأولى: الصفحة الرئيسية",
      delivery: "Live Demo",
      deliveryStatus: "مقبولة",
      deliveryTone: "accepted" as const,
      paymentStatus: "Ready to Release",
      paymentTone: "ready" as const,
      amount: "$250",
      lastUpdate: "أمس",
      actionLabel: "عرض التفاصيل",
    },
    {
      id: "delivery-004",
      project: "تصميم لوحة تحكم SaaS",
      client: "منصة بيان",
      milestone: "المرحلة الثالثة: التصميم النهائي",
      delivery: "بانتظار الإرسال",
      deliveryStatus: "بانتظار التسليم",
      deliveryTone: "pending" as const,
      paymentStatus: "Reserved",
      paymentTone: "reserved" as const,
      amount: "$400",
      lastUpdate: "اليوم",
      actionLabel: "تقديم تسليم",
    },
    {
      id: "delivery-005",
      project: "كتابة محتوى صفحة بيع",
      client: "شركة نمو",
      milestone: "المرحلة الأولى: نسخة أولية",
      delivery: "Google Doc",
      deliveryStatus: "AI Review",
      deliveryTone: "ai" as const,
      paymentStatus: "AI Review",
      paymentTone: "ai" as const,
      amount: "$120",
      lastUpdate: "منذ يومين",
      actionLabel: "عرض مراجعة AI",
    },
  ],
  selectedSummary: {
    title: "ملخص التسليم المحدد",
    project: "تصميم صفحة هبوط لشركة ناشئة",
    milestone: "المرحلة الأولى: الهيكل والتصميم الأولي",
    statusLabel: "الحالة",
    status: "تحت مراجعة العميل",
    paymentLabel: "الدفعة",
    payment: "Client Review",
    amount: "$150",
    deliveryTimeLabel: "وقت التسليم",
    deliveryTime: "منذ ساعتين",
    reviewDueLabel: "موعد المراجعة",
    reviewDue: "بعد 3 أيام عمل",
    criteriaTitle: "شروط القبول",
    criteria: ["تسليم Wireframe واضح للصفحة", "تحديد أقسام الصفحة الرئيسية", "اعتماد الاتجاه البصري الأولي"],
    note: "بانتظار مراجعة العميل للتسليم.",
  },
  aiNotice: "إذا اعترض العميل، يمكن فتح AI Review وربط الاعتراض بشروط القبول.",
  quickActionsTitle: "إجراءات سريعة",
  quickActions: ["فتح التسليم", "نسخ رابط التسليم", "فتح مساحة العمل"],
} as const satisfies DeliveriesContent;