import type { DeliveriesContent } from "@/types";

export const deliveriesContent = {
  title: "التسليمات",
  subtitle: "تابع كل تسليمات المراحل، مراجعات العملاء، وحالة الدفعات المرتبطة بها.",
  searchPlaceholder: "ابحث باسم المشروع أو العميل...",
  exportLabel: "تصدير التقرير",
  createLabel: "تقديم تسليم جديد",
  metrics: [
    { label: "بانتظار التسليم", value: "3", helper: "مراحل جاهزة للتسليم", badge: "انتباه", tone: "amber" },
    { label: "تحت مراجعة العميل", value: "2", helper: "تسليمات تم إرسالها", badge: "نشط", tone: "violet" },
    { label: "مقبولة", value: "5", helper: "دفعات جاهزة أو مصروفة", badge: "مكتمل", tone: "emerald" },
    { label: "تحتاج إجراء", value: "1", helper: "طلب تعديل أو اعتراض", badge: "عاجل", tone: "red" },
  ],
  filters: [
    { label: "الكل", count: "5", active: true },
    { label: "بانتظار التسليم", count: "3" },
    { label: "تحت مراجعة العميل", count: "2" },
    { label: "مقبولة", count: "5" },
    { label: "طلب تعديل", count: "1" },
    { label: "AI Review", count: "1" },
  ],
  sortFilters: ["كل الاتفاقات", "كل العملاء", "آخر 30 يوم", "الأحدث أولاً"],
  tableHeaders: ["المشروع / العميل", "المرحلة", "التسليم", "حالة التسليم", "حالة الدفعة", "المبلغ", "آخر تحديث", "الإجراء"],
  deliveries: [
    {
      id: "delivery-001",
      project: "تصميم صفحة هبوط لشركة ناشئة",
      client: "شركة المدار",
      milestone: "المرحلة الأولى: الهيكل والتصميم الأولي",
      delivery: "رابط Figma",
      deliveryStatus: "تحت مراجعة العميل",
      deliveryTone: "review",
      paymentStatus: "Client Review",
      paymentTone: "client",
      amount: "$150",
      lastUpdate: "منذ ساعتين",
      actionLabel: "عرض التسليم",
      active: true,
    },
    {
      id: "delivery-002",
      project: "هوية بصرية لمتجر إلكتروني",
      client: "متجر نوفا",
      milestone: "المرحلة الثانية: النماذج النهائية",
      delivery: "ZIP + Drive",
      deliveryStatus: "طلب تعديل",
      deliveryTone: "change",
      paymentStatus: "On Hold",
      paymentTone: "hold",
      amount: "$300",
      lastUpdate: "منذ 5 ساعات",
      actionLabel: "مراجعة طلب التعديل",
    },
    {
      id: "delivery-003",
      project: "تطوير موقع تعريفي",
      client: "شركة روافد",
      milestone: "المرحلة الأولى: الصفحة الرئيسية",
      delivery: "Live Demo",
      deliveryStatus: "مقبولة",
      deliveryTone: "accepted",
      paymentStatus: "Ready to Release",
      paymentTone: "ready",
      amount: "$250",
      lastUpdate: "أمس",
      actionLabel: "عرض التفاصيل",
    },
    {
      id: "delivery-004",
      project: "تصميم لوحة تحكم SaaS",
      client: "منصة بيان",
      milestone: "المرحلة الثالثة: التصميم النهائي",
      delivery: "بانتظار الإرسال",
      deliveryStatus: "بانتظار التسليم",
      deliveryTone: "pending",
      paymentStatus: "Reserved",
      paymentTone: "reserved",
      amount: "$400",
      lastUpdate: "اليوم",
      actionLabel: "تقديم تسليم",
    },
    {
      id: "delivery-005",
      project: "كتابة محتوى صفحة بيع",
      client: "شركة نمو",
      milestone: "المرحلة الأولى: نسخة أولية",
      delivery: "Google Doc",
      deliveryStatus: "AI Review",
      deliveryTone: "ai",
      paymentStatus: "AI Review",
      paymentTone: "ai",
      amount: "$120",
      lastUpdate: "منذ يومين",
      actionLabel: "عرض مراجعة AI",
    },
  ],
  selectedSummary: {
    title: "ملخص التسليم المحدد",
    project: "تصميم صفحة هبوط لشركة ناشئة",
    milestone: "المرحلة الأولى: الهيكل والتصميم الأولي",
    statusLabel: "الحالة",
    status: "تحت مراجعة العميل",
    paymentLabel: "الدفعة",
    payment: "Client Review",
    amount: "$150",
    deliveryTimeLabel: "وقت التسليم",
    deliveryTime: "منذ ساعتين",
    reviewDueLabel: "موعد المراجعة",
    reviewDue: "بعد 3 أيام عمل",
    criteriaTitle: "شروط القبول",
    criteria: ["تسليم Wireframe واضح للصفحة", "تحديد أقسام الصفحة الرئيسية", "اعتماد الاتجاه البصري الأولي"],
    note: "بانتظار مراجعة العميل للتسليم.",
  },
  aiNotice: "إذا اعترض العميل، يمكن فتح AI Review وربط الاعتراض بشروط القبول.",
  quickActionsTitle: "إجراءات سريعة",
  quickActions: ["فتح التسليم", "نسخ رابط التسليم", "فتح مساحة العمل"],
} as const satisfies DeliveriesContent;
