import type { DeliveriesContent } from "@/types";

export const deliveriesContent = {
  title: "التسليمات",
  subtitle: "تابع كل تسليمات المراحل، مراجعات العملاء، وحالة الدفعات المرتبطة بها.",
  searchPlaceholder: "الفلاتر المدعومة من الخادم تظهر أسفل الصفحة",
  exportLabel: "عرض البيانات الحية",
  createLabel: "ابدأ من مساحة العمل",
  metrics: [],
  filters: [],
  sortFilters: [],
  tableHeaders: ["المشروع / العميل", "المرحلة", "التسليم", "حالة التسليم", "حالة الدفعة", "المبلغ", "آخر تحديث", "الإجراء"],
  deliveries: [],
  selectedSummary: {
    title: "ملخص التسليم المحدد",
    project: "سيظهر اسم الاتفاق هنا",
    milestone: "ستظهر المرحلة المرتبطة هنا",
    statusLabel: "الحالة",
    status: "اختر تسليماً لعرض التفاصيل",
    paymentLabel: "الدفعة",
    payment: "ستظهر من البيانات الحية",
    amount: "--",
    deliveryTimeLabel: "وقت التسليم",
    deliveryTime: "--",
    reviewDueLabel: "موعد المراجعة",
    reviewDue: "--",
    criteriaTitle: "شروط القبول",
    criteria: [],
    note: "سيظهر وصف التسليم أو ملاحظات العميل عند تحديد عنصر من الجدول.",
  },
  aiNotice: "إذا اعترض العميل، يمكن فتح AI Review وربط الاعتراض بشروط القبول.",
  quickActionsTitle: "إجراءات سريعة",
  quickActions: ["فتح التسليم", "فتح المرحلة", "العودة لمساحة العمل"],
} as const satisfies DeliveriesContent;
